### ISSUE TITLE
genmsg ignores files in add_message_files

### ISSUE THREAD

**Issue by tkruse** [ros/genmsg#16] opened 2013-01-19 11:14 UTC
To reproduce:

``` shell
mkdir genmsg_ws
cd genmsg_ws/
mkdir src
cd src
git clone https://github.com/ros/catkin.git
git clone https://github.com/ros/genmsg.git
catkin_create_pkg foo message_generation roscpp rospy
cd foo
mkdir msg
cd msg
echo "Header header
float32 pressure # [C]
float32 temperature # [kPa]" > bar.msg
cd ..
rm CMakeLists.txt
echo "cmake_minimum_required(VERSION 2.8.3)
project(foo)
find_package(catkin REQUIRED COMPONENTS message_generation roscpp rospy)
add_message_files(
  FILES
  foo1.msg
  foo2.msg
  foo3.msg
)
generate_messages(
  DEPENDENCIES
  std_msgs  # Or other packages containing msgs
)
catkin_package()" > CMakeLists.txt
cd ../..
. /opt/ros/groovy/setup.bash 
catkin_make
```

yields 

```
-- catkin 0.5.62
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing packages in topological order:
-- ~~  - foo
-- ~~  - genmsg
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
[ 25%] [ 75%] [ 75%] Generating Python from MSG foo/bar
Generating Lisp code from foo/bar.msg
Generating C++ code from foo/bar.msg
```

should fail due to missing foo1.msg, foo2.msg, foo3.msg

**Comment by dirk-thomas** [comment] 2013-01-19 18:42
Duplicate of #18

**Closed as completed by dirk-thomas** 2013-01-19 18:42 UTC
