### ISSUE TITLE
Should warn when calling generate_messages() before add_service_files

### ISSUE THREAD

**Issue by chadrockey** [ros/genmsg#19] opened 2013-01-22 21:59 UTC
If you call generate_messages() before calling add_service_files(...), then the error you get is the following:

imu_drivers_catkin/src/microstrain_3dmgx2_imu/imu_node.cc:55:46: fatal error: microstrain_3dmgx2_imu/AddOffset.h: No such file or directory
compilation terminated.

There should be a warning if you call generate_messages() and have not added message or service files.

**Comment by dirk-thomas** [comment] 2013-01-29 02:58
Calling generate_messages() with zero messages/services should not be a warning since depending on the users CMake it is feasible to enable/disable certain messages which could lead to zero. genmsg already outputs the number of processed message and service files which should be enough for the user to figure out what is wrong if zero is not the desired number of messages.

Adding a message for the wrong order is a duplicate of #22.

**Closed as completed by dirk-thomas** 2013-01-29 02:58 UTC
